# Generated by Django 3.2.7 on 2021-09-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lotSize', models.CharField(max_length=150)),
                ('lotNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimatedCompletionDate', models.DateField()),
                ('estimatedCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('itemsReceived', models.TextField()),
                ('note', models.CharField(max_length=100)),
                ('contactNumber', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.lot')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.super')),
            ],
        ),
        migrations.CreateModel(
            name='LotNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.lot')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.note')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.project'),
        ),
        migrations.AddField(
            model_name='lot',
            name='super',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.super'),
        ),
    ]
