# Generated by Django 3.2.7 on 2021-09-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFocusapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lotId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectFocusapi.lot'),
        ),
    ]
