# Generated by Django 3.2.7 on 2021-09-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFocusapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='lotNote',
            new_name='lotId',
        ),
    ]
