# Generated by Django 3.2.7 on 2021-09-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFocusapi', '0002_alter_note_lotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.ManyToManyField(through='projectFocusapi.ProjectNote', to='projectFocusapi.Note'),
        ),
    ]
